pull_request_rules:
- name: auto-merge
  description: automatic merge
  conditions:
    - "#approved-reviews-by>=1"
  actions:
    merge:
      method: merge
      commit_message_template: |
        {{ title }} (#{{ number }})

        {{ body }}

        {% for user in approved_reviews_by %}
        Approved-By: {{user}} <{{user.email}}> {{ user.login }} {{ user.name }} {{ user.id }}
        {% endfor %}
    delete_head_branch:

- name: automatic approval
  conditions:
    - label=approve
  actions:
    review:
      type: APPROVE
