pull_request_rules:
- name: auto-merge
  description: automatic merge
  conditions:
    - "#approved-reviews-by>=1"
  actions:
    merge:
      method: merge
      commit_message_template: |
        {{ title }} (#{{ number }})

        {{ body }}

        {% for user in approved_reviews_by %}
        {% if user == "leseb" %}
        Approved-by: "Sébastien Han <seb@redhat.com>"
        {% elif user == "mergify[bot]" %}
        Approved-by: mergiyo!
        {% else %}
        Approved-by: {{ user }}
        {% endif %}
        {% endfor %}
    delete_head_branch:

- name: automatic approval
  conditions:
    - label=approve
  actions:
    review:
      type: APPROVE
