pull_request_rules:
- name: auto-merge
  description: automatic merge
  conditions:
    - "#approved-reviews-by>=1"
  actions:
    merge:
      method: merge
      commit_message_template: |
        {{ title }} (#{{ number }})

        {{ body }}

        {% set approval_messages = {
            "leseb": "Sébastien Han <seb@redhat.com>",
            "mergify[bot]": "mergiyo!"
        } %}

        {% for user in approved_reviews_by %}
        Approved-by: {{ approval_messages.get(user, user) }}
        {% endfor %}
    delete_head_branch:

- name: automatic approval
  conditions:
    - label=approve
  actions:
    review:
      type: APPROVE
